import type { Project } from "./project";

export function createExportPlayerHtml(project: Project) {
  const data = JSON.stringify(project).replace(/</g, "\\u003c");
  const title = escapeHtml(project.title);
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>
html,body,#app{margin:0;width:100%;height:100%;background:#080a0d;color:#fff;font-family:system-ui,"Microsoft YaHei"}#app{display:grid;place-items:center}.stage{width:min(100vw,1200px);aspect-ratio:16/9;position:relative;background:#18212a center/cover no-repeat;overflow:hidden}.stage video,.stage img{width:100%;height:100%;object-fit:contain}.dialog,.interaction{position:absolute;left:6%;right:6%;bottom:6%;padding:18px;background:rgba(5,7,9,.86)}button{display:block;width:min(80%,520px);margin:10px auto;padding:14px;border:1px solid ${project.ui.accent};border-radius:${project.ui.buttonRadius}px;background:#111c;color:#fff}.ending{text-align:center}.timer{text-align:center;color:#ffd36b}
</style></head><body><div id="app"></div><script>const project=${data};if(project.schemaVersion!==2)throw new Error('unsupported schemaVersion');const app=document.querySelector('#app'),nodes=new Map(project.nodes.map(n=>[n.id,n])),edges=new Map(project.edges.map(e=>[e.source+':'+e.sourcePort,e.target])),chapters=new Map(project.nodes.filter(n=>n.kind==='chapter').map(n=>[n.chapterId,n.id]));let vars={},timer,music;const next=(id,p)=>edges.get(id+':'+p),asset=id=>project.assets.find(a=>a.id===id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function compare(l,o,r){if(o==='eq')return l===r;if(o==='neq')return l!==r;if(o==='contains')return String(l).includes(String(r));if(o==='notContains')return !String(l).includes(String(r));if(o==='gt')return Number(l)>Number(r);if(o==='gte')return Number(l)>=Number(r);if(o==='lt')return Number(l)<Number(r);return Number(l)<=Number(r)}
function apply(n){const p=vars[n.variableId]??0,v=n.value;if(n.operation==='set')vars[n.variableId]=v;else if(n.operation==='append')vars[n.variableId]=String(p)+String(v);else if(n.operation==='toggle')vars[n.variableId]=!Boolean(p);else if(n.operation==='add')vars[n.variableId]=Number(p)+Number(v);else if(n.operation==='subtract')vars[n.variableId]=Number(p)-Number(v);else if(n.operation==='multiply')vars[n.variableId]=Number(p)*Number(v);else vars[n.variableId]=Number(p)/Number(v)}
function audio(n){if(n.kind==='music'){if(n.action==='stop'){music?.pause();music=undefined}else if(n.action==='fadeOut'){music?.pause();music=undefined}else{const a=asset(n.assetId);if(a){music?.pause();music=new Audio(a.url);music.loop=true;music.volume=n.volume;music.play().catch(()=>{})}}}else{const a=asset(n.assetId);if(a){const s=new Audio(a.url);s.volume=n.volume;s.play().catch(()=>{})}}}
function go(id,depth=0){clearTimeout(timer);if(depth>1000)return fail('自动节点循环');const n=nodes.get(id);if(!n)return fail('剧情连接异常');if(n.kind==='start'||n.kind==='chapter')return go(next(n.id,'next'),depth+1);if(n.kind==='jump')return go(chapters.get(n.chapterId),depth+1);if(n.kind==='setVariable'){apply(n);return go(next(n.id,'next'),depth+1)}if(n.kind==='condition')return go(next(n.id,compare(vars[n.variableId]??0,n.operator,n.value)?'true':'false'),depth+1);if(n.kind==='random'){let total=n.branches.reduce((s,b)=>s+b.weight,0),cursor=Math.random()*total,port=n.branches[0].id;for(const b of n.branches){cursor-=b.weight;if(cursor<0){port=b.id;break}}return go(next(n.id,port),depth+1)}if(n.kind==='music'||n.kind==='sound'){audio(n);return go(next(n.id,'next'),depth+1)}if(n.kind==='wait'){app.innerHTML='<div class="stage interaction"><p>等待 '+n.durationMs/1000+' 秒</p><button id="skip">跳过等待</button></div>';document.querySelector('#skip').onclick=()=>go(next(n.id,'next'));timer=setTimeout(()=>go(next(n.id,'next')),n.durationMs);return}render(n)}
function render(n){if(n.kind==='scene'){const a=asset(n.assetId),media=a?(a.type.startsWith('video/')?'<video autoplay muted src="'+esc(a.url)+'"></video>':'<img src="'+esc(a.url)+'">'):'';app.innerHTML='<div class="stage">'+media+(n.showDialogue?'<div class="dialog"><b>'+esc(n.speaker)+'</b><p>'+esc(n.dialogue)+'</p><button id="next">继续</button></div>':a?.type.startsWith('video/')?'':'<button id="next">继续</button>')+'</div>';const video=document.querySelector('video'),button=document.querySelector('#next');if(video&&!n.showDialogue)video.onended=()=>go(next(n.id,'next'));if(button)button.onclick=()=>go(next(n.id,'next'));return}if(n.kind==='choice'||n.kind==='timedChoice'){app.innerHTML='<div class="stage"><div class="interaction">'+(n.kind==='timedChoice'?'<p class="timer">限时 '+n.durationMs/1000+' 秒</p>':'')+'<p>'+esc(n.prompt)+'</p>'+n.choices.map(c=>'<button data-port="'+esc(c.id)+'">'+esc(c.label)+'</button>').join('')+'</div></div>';document.querySelectorAll('[data-port]').forEach(b=>b.onclick=()=>go(next(n.id,b.dataset.port)));if(n.kind==='timedChoice')timer=setTimeout(()=>go(next(n.id,'timeout')),n.durationMs);return}if(n.kind==='ending')app.innerHTML='<div class="ending"><small>结局达成</small><h1>'+esc(n.endingTitle)+'</h1><button id="restart">重新开始</button></div>',document.querySelector('#restart').onclick=start}
function fail(message){app.innerHTML='<h2>'+esc(message)+'</h2>'}function start(){clearTimeout(timer);vars=Object.fromEntries(project.variables.map(v=>[v.id,v.initialValue]));go(project.nodes.find(n=>n.kind==='start')?.id)}start();<\/script></body></html>`;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
}
